# Generated by Django 3.2.15 on 2022-09-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220919_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_profile',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_profile',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_profile',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
