# Generated by Django 3.2.15 on 2022-09-21 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20220920_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_profile',
            new_name='facebook_handle',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram_profile',
            new_name='instagram_handle',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter_profile',
            new_name='twitter_handle',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subbed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
