# Generated by Django 3.2.15 on 2022-09-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220921_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_handle',
            new_name='youtube_handle',
        ),
    ]
