# Generated by Django 3.2.15 on 2022-09-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_facebook_handle_profile_youtube_handle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='masthead',
        ),
    ]
